openapi: 3.0.3
info:
  contact:
    email: info@lingvanex.com
  description: |-
    Lingvanex works via HTTPS requests. The URL of all requests starts with https://api-b2b.backenster.com/b1/api/v3/. In case of a protocol selection error and using HTTP, the request will be redirected to the address with the HTTPS protocol (status code 302). <br><br>Authentication of requests is done by adding the “Authorization” header with the following data format: Bearer The key can be created on the user control panel page https://lingvanex.com/account.
    Example: "Authorization: Bearer <YOUR_API_KEY>".
  termsOfService: https://lingvanex.com/terms-of-service/
  title: Lingvanex Cloud API
  version: 1.0.0
servers:
- url: https://api-b2b.backenster.com/b1/api/v3
- url: http://api-b2b.backenster.com/b1/api/v3
security:
- APIKeyHeader: []
paths:
  /getLanguages:
    get:
      parameters:
      - description: api
        explode: true
        in: query
        name: platform
        required: true
        schema:
          default: api
          type: string
        style: form
      - description: "the language code in the format “language code_code of the country”\
          , which is used to display the names of the languages. The language code\
          \ is represented only in lowercase letters, the country code only in uppercase\
          \ letters (example en_GB, es_ES, ru_RU etc). If this option is not present,\
          \ then English is used by default"
        explode: true
        in: query
        name: code
        required: false
        schema:
          default: en_GB
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_getLanguages_get_200_response'
          description: Success
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
          description: Authorization error. You should add the API_KEY to request
            which can be created on the user control panel page https://lingvanex.com/account
      summary: Getting the list of languages
      tags:
      - Get languages
  /translate:
    post:
      description: "This method translates text and HTML single string or arrays.\
        \ Also it performs transliteration, language auto detection. Please, check\
        \ request examples on the right to check these capabilities."
      requestBody:
        content:
          application/json:
            examples:
              Translate text:
                value:
                  from: en_GB
                  to: de_DE
                  data: London is the capital and largest city of England and of the
                    United Kingdom.
                  platform: api
              Translate text array:
                value:
                  from: en_GB
                  to: de_DE
                  data:
                  - London is the capital and largest city of England and of the United
                    Kingdom.
                  - Hello World!
                  platform: api
              Translate and transliterate text:
                value:
                  from: en_GB
                  to: de_DE
                  data: 'London is the capital and largest city of England and of
                    the United Kingdom.                  '
                  platform: api
                  enableTransliteration: true
              Translate text and auto detect language:
                value:
                  to: de_DE
                  data: London is the capital and largest city of England and of the
                    United Kingdom.
                  platform: api
              Translate html:
                value:
                  from: en_GB
                  to: de_DE
                  translateMode: html
                  data: <h1>London is the capital and largest city of England and
                    of the United Kingdom.</h1>
                  platform: api
              Translate html array:
                value:
                  from: en_GB
                  to: de_DE
                  translateMode: html
                  data:
                  - <h1>London is the capital and largest city of England and of the
                    United Kingdom.</h1>
                  - <h1>Hello World!</h1>
                  platform: api
            schema:
              $ref: '#/components/schemas/_translate_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_translate_post_200_response'
          description: success
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthError'
          description: Authorization error. You should add the API_KEY to request
            which can be created on the user control panel page https://lingvanex.com/account
      summary: Translate
      tags:
      - "Translate (text, HTML, transliterate, auto detection)"
components:
  schemas:
    AuthError:
      example:
        err: Token absent
      properties:
        err:
          description: "the text of the error. It is null if the response status is\
            \ 200. Otherwise, it contains a string"
          type: string
    _getLanguages_get_200_response_result_inner_modes_inner:
      properties:
        name:
          description: "name of the function. Currently, only 4 functions are widely\
            \ supported: “Speech synthesis“, “Image recognition“, “Translation“, “\
            Speech recognition“"
          type: string
        value:
          description: "logical value true or false, which shows the status of the\
            \ function: on or off"
          type: boolean
        genders:
          description: "logical value true or false, which shows the ability to synthesize\
            \ speech for both sexes. Displayed only for function “Speech synthesis“"
          type: boolean
      type: object
    _getLanguages_get_200_response_result_inner:
      properties:
        full_code:
          description: the language code in the format “language code_code of the
            country”
          type: string
        code_alpha_1:
          description: the language code in the “language code” format
          type: string
        englishName:
          description: English name of the language
          type: string
        codeName:
          description: the language name translated using the language specified by
            the query parameter “code”
          type: string
        flagPath:
          description: "the relative address of which is the image of the country\
            \ flag. Example static/flags/afrikaans. The full address for downloading\
            \ the flag will be https://backenster.com/v2/static/flags/afrikaans.png.\
            \ In order to download flags in increased resolutions, you should add\
            \ to this parameter: @2x or @3x (example https://backenster.com/v2/static/flags/afrikaans@2x.png\
            \ or  https://backenster.com/v2/static/flags/afrikaans@3x.png)"
          type: string
        testWordForSyntezis:
          description: a word for testing a speech synthesizer
          type: string
        modes:
          description: "an array of objects, each of which is a description of the\
            \ function that is supported in the given language"
          items:
            $ref: '#/components/schemas/_getLanguages_get_200_response_result_inner_modes_inner'
          type: array
      type: object
    _getLanguages_get_200_response:
      example:
        result:
        - full_code: en_GB
          name: en
          englishName: Afrikaans
          codeName: Afrikaans
          flagPath: static/flags/afrikaans
          testWordForSyntezis: Hallo
          modes:
          - name: Translation
            value: true
            genders: true
        err: err
      properties:
        err:
          description: "the text of the error. It is null if the response status is\
            \ 200. Otherwise, it contains a string"
          type: string
          example: null
        result:
          example:
          - full_code: en_GB
            name: en
            englishName: Afrikaans
            codeName: Afrikaans
            flagPath: static/flags/afrikaans
            testWordForSyntezis: Hallo
            modes:
            - name: Translation
              value: true
              genders: true
          items:
            $ref: '#/components/schemas/_getLanguages_get_200_response_result_inner'
          type: array
      type: object
    _translate_post_request_data:
      description: data for translation
      oneOf:
      - type: string
      - items:
          type: string
        type: array
    _translate_post_request:
      properties:
        from:
          description: "the language code in the format “language code_code of the\
            \ country” from which the text is translated. The language code is represented\
            \ only in lowercase letters, the country code only in uppercase letters\
            \ (example en_GB, es_ES, ru_RU and etc.). If this parameter is not present,\
            \ the auto-detect language mode is enabled"
          type: string
        to:
          description: language code in the format “language code_code of the country”
            to which the text is translated (required)
          type: string
        data:
          $ref: '#/components/schemas/_translate_post_request_data'
        translateMode:
          description: 'Describe the input text format. Possible value is "html" for  translating
            and preserving html structure. If value is not  specified or is other
            than "html" than plain text is translating.  '
          enum:
          - html
          type: string
        enableTransliteration:
          description: |-
            If true response includes sourceTransliteration and targetTransliteration fields.
                      platform:
          type: boolean
        platform:
          default: api
          description: api
          type: string
      required:
      - data
      - platform
      - to
      type: object
    _translate_post_200_response_result:
      description: "result of translation. In the event that a line was sent to the\
        \ translation, the result is also a string; if an array of strings, then we\
        \ also get an array of strings"
      oneOf:
      - type: string
      - items:
          type: string
        type: array
    _translate_post_200_response:
      example:
        err: null
        result: London ist die Hauptstadt und größte Stadt Englands und des Vereinigten
          Königreichs.
        sourceTransliteration: London is the capital and largest city of England and
          of the United Kingdom.
        targetTransliteration: London ist die Hauptstadt und grosste Stadt Englands
          und des Vereinigten Konigreichs.
      properties:
        err:
          description: "the text of the error. It is null if the response status is\
            \ 200. Otherwise, it contains a string"
          type: string
        result:
          $ref: '#/components/schemas/_translate_post_200_response_result'
        sourceTransliteration:
          description: "return only if enableTransliteration request param is true.\
            \ Transliteration of source data. In the event that a line was sent to\
            \ the translation, the result is also a string; if an array of strings,\
            \ then we also get an array of strings"
          type: string
        targetTransliteration:
          description: "return only if enableTransliteration request param is true.\
            \ Transliteration results. In the event that a line was sent to the translation,\
            \ the result is also a string; if an array of strings, then we also get\
            \ an array of strings"
          type: string
      required:
      - err
      - result
      type: object
  securitySchemes:
    APIKeyHeader:
      in: header
      name: Authorization
      type: apiKey
x-readme:
  explorer-enabled: true
  proxy-enabled: true
